version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_reverse_proxy
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./data/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/conf.d/:/etc/nginx/conf.d/
      - ./data/certs/:/certs